name: arduino-k210 core build and autotest, based on ESP32 Arduino CI

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '.github/workflows/docs.yml'
      - 'docs/**'

  pull_request:
    branches:
      - 'main'
    paths-ignore:
      - '.github/workflows/docs.yml'
      - 'docs/**'

concurrency:
  group: build-${{github.event.pull_request.number || github.ref}}
  cancel-in-progress: true

jobs:

  build-arduino:
    name: Arduino Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, windows-latest, macOS-latest]
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Build Sketches
      run: |
        bash ./tools/on-push.sh

